version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - n 18
  pre_build:
    commands:
      - cd src/wordly-spa
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "build/**/*"

image: aws/codebuild/standard:5.0