version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - n 18
      - cd src/wordly-spa
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "build/**/*"